apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus_container:9090  # Указываем на Prometheus контейнер в сети
    isDefault: true
    editable: true