apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mlops-namespace
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'model'
        static_configs:
          - targets: ['model-service:8000']