apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: mlops-namespace
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP