name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - main  # Запуск Workflow при пуше в ветку main
  workflow_dispatch:  # Включение ручного запуска через интерфейс GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest  # Использование Ubuntu для выполнения пайплайна

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Вход в DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Шаг 3: Настройка AWS CLI (если нужно)
      - name: Set up AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "region = eu-central-1" >> ~/.aws/config
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Шаг 4: Подключение к EC2 через SSH и деплой
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ec2-18-159-134-62.eu-central-1.compute.amazonaws.com  # IP или DNS EC2
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Удаление старого контейнера, если он существует
            docker rm -f mlopsclassification-model || true

            # Загрузка последнего образа модели из Docker Hub
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mlopsclassification-model:latest

            # Запуск нового контейнера
            docker run -d --name mlopsclassification-model --network="host" -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/mlopsclassification-model:latest