name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  workflow_dispatch:  # Enable manual triggering of the workflow through GitHub Actions interface

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu for running GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clone the repository to access files and scripts

      - name: Log in to Docker Hub  # Log in to Docker Hub to access container images
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Docker Hub username from secrets
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Docker Hub access token from secrets

      - name: Set up SSH for EC2  # Set up SSH connection to access EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7  # Connect to EC2 via SSH
        with:
          host: 18.159.134.62  # Public IP or DNS name of your EC2
          username: ec2-user