name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Branch that triggers the GitHub Action on push events

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the environment for the GitHub Action to run on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clone the repository to access files and scripts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for building multi-platform images

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Docker Hub username stored in GitHub secrets
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Docker Hub access token stored in GitHub secrets

      - name: Build and push Docker image for mlops_classification-model
        uses: docker/build-push-action@v2
        with:
          context: .  # Build context set to the root directory
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mlops_classification-model:latest  # Tag for the model image

      - name: Build and push Docker image for mlops_classification-database
        uses: docker/build-push-action@v2
        with:
          context: .  # Build context set to the root directory
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mlops_classification-database:latest  # Tag for the database image

      - name: Build and push Docker image for mlops-prometheus
        uses: docker/build-push-action@v2
        with:
          context: .  # Build context set to the root directory
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-prometheus:latest  # Tag for the Prometheus image

      - name: Build and push Docker image for mlops-grafana
        uses: docker/build-push-action@v2
        with:
          context: .  # Build context set to the root directory
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-grafana:latest  # Tag for the Grafana image

      - name: Log out from Docker Hub
        run: docker logout  # Log out from Docker Hub after pushing the images